// <auto-generated />
using System;
using CW7924.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(FlowerShopDbContext))]
    [Migration("20210215062551_fdb")]
    partial class fdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.DBO.Client", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("DateOfBirth")
                    .HasColumnType("datetime2");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Gender")
                    .HasColumnType("int");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("PlantId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PlantId");

                b.ToTable("Clients");
            });

            modelBuilder.Entity("DAL.DBO.Plant", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("PlantName")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("PlantType")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Plants");
            });

            modelBuilder.Entity("DAL.DBO.Client", b =>
            {
                b.HasOne("DAL.DBO.Plant", null)
                    .WithMany("Clients")
                    .HasForeignKey("PlantId");
            });
#pragma warning restore 612, 618
        }
    }
}
